### ISSUE TITLE
Error with home assistant 2024.11.3

### ISSUE THREAD

**Issue by carlituxman** [marcosav/fermax-blue-intercom#6]
with home asistant 2024.11.3 throw this

stdout: ""
stderr: >-
  /config/scripts/open_door.py:632: DeprecationWarning: There is no current
  event loop
    loop = asyncio.get_event_loop()
  /config/scripts/open_door.py:259: DeprecationWarning:
  datetime.datetime.utcnow() is deprecated and scheduled for removal in a future
  version. Use timezone-aware objects to represent datetimes in UTC:
  datetime.datetime.now(datetime.UTC).
    or datetime.datetime.utcnow() >= self._token_data.expires_at
returncode: 0

**Comment by marcosav** [comment]
@carlituxman I think its solved, try again and let me know if it doesn't work, thank you

**Comment by carlituxman** [comment]
works but throw this:

stdout: ""
stderr: >-
  /config/scripts/open_door.py:635: DeprecationWarning: There is no current
  event loop
    loop = asyncio.get_event_loop()
returncode: 0

**Comment by marcosav** [comment]
@carlituxman fixed, I have tried it with HA 2024.11.3 and working again

**Comment by carlituxman** [comment]
Yes!. working.

stdout: ""
stderr: ""
returncode: 0
